### ISSUE TITLE
zero_bss creates inefficient code

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/r0#3]
`zero_bss` uses `ptr::write_bytes` which does exactly what it says, namely writing an arbitrary number of bytes to an potentially unaligned memory address. While the compiler seems to be able to detect that we want to zero out memory, hence calling (for arm-eabi targets) `__aeabi_memclr4`, this implementation simply loads a zero into a register and then calls `__aeabi_memset4` which does all sorts of madness including the alignment of memory and setting trailing bytes if the number bytes mod register size is not equal zero.

An halfway small but dumb implementation could simply set a register to 0, loop over all addresses from start to end in strides of the largest register size and write the register value to the address. That would remove one of the largest bloat items of embedded binaries...

**Comment by japaric** [comment]
Changing `zero_bss` to:

``` rust
pub unsafe fn zero_bss(mut sbss: *mut usize, ebss: *mut usize) {
    while sbss < ebss {
        ptr::write_volatile(sbss, 0);
        sbss = sbss.offset(1);
    }
}
```

produces:

``` armasm
08000400 <cortex_m_rt::reset_handler>:
 8000400:       f240 0000       movw    r0, #0
 8000404:       f240 0100       movw    r1, #0
 8000408:       f2c2 0000       movt    r0, #8192       ; 0x2000
 800040c:       f2c2 0100       movt    r1, #8192       ; 0x2000
 8000410:       4281            cmp     r1, r0
 8000412:       d208            bcs.n   8000426 <cortex_m_rt::reset_handler+0x26>
 8000414:       f240 0100       movw    r1, #0
 8000418:       2200            movs    r2, #0
 800041a:       f2c2 0100       movt    r1, #8192       ; 0x2000
 800041e:       f841 2b04       str.w   r2, [r1], #4
 8000422:       4281            cmp     r1, r0
 8000424:       d3fb            bcc.n   800041e <cortex_m_rt::reset_handler+0x1e>
 8000426:       e7fe            b.n     8000426 <cortex_m_rt::reset_handler+0x26>
```

(the second R1 mov seems unnecessary?)

for

``` rust
fn reset_handler() {
    zero_bss(sbss, ebss);
    loop {}
}
```

but I think this `zero_bss` won't do the right thing for AVR where `usize` is 16 bits and the register size is 8 bits.

OK. Maybe this is better:

``` rust
pub unsafe fn zero_bss<T>(mut sbss: *mut T, ebss: *mut T)
where
    T: Copy,
{
    while sbss < ebss {
        ptr::write_volatile(sbss, mem::zeroed());
        sbss = sbss.offset(1);
    }
}
```

Produces the same thing but doesn't break the current API and should work with AVR (T = u8).
