### ISSUE TITLE
Ship a 1.0 release

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/r0#9]
Part of https://github.com/rust-embedded/wg/issues/383

Blockers:

* [x] specify our MSRV
* [x] add `readme` field to manifest
* [x] Review against https://rust-lang.github.io/api-guidelines/ – https://github.com/rust-embedded/r0/issues/12
* [x] document requirements around `<T: Copy>` for `init_data` and `zero_bss`
* [x] ~~document~~ rip out `init_array` and friends

**Comment by jonas-schievink** [comment]
I've done a short review of the API:

* `init_array`, `pre_init_array` and `run_init_array` are undocumented and (AFAIK) not really used in the Rust world. Do we want to remove them?
* `init_data` and `zero_bss` take a `T: Copy` parameter for which all `T`-sized byte sequences, or `mem::zeroed()` must be a valid inhabitant, respectively. This should be documented and ideally enforced via an additional trait bound. Practically `T` is always set to some unsigned integer type of machine word size, I think.
  * The additional trait bound could also enfore the "`mem::size_of::<T>()` must be non-zero" invariant at compiletime

**Comment by Disasm** [comment]
Maybe `#[inline(always)]` would be great for all the methods. They are called once anyway.

**Comment by therealprof** [comment]
> Maybe `#[inline(always)]` would be great for all the methods. They are called once anyway.

I like the ability to see how much binary size is attributed to those functions, also it's quite handy to set breakpoints on them. I'd really only force-inline them if there's a universal and substantial code size improvement.

**Comment by almindor** [comment]
> > Maybe `#[inline(always)]` would be great for all the methods. They are called once anyway.
> 
> I like the ability to see how much binary size is attributed to those functions, also it's quite handy to set breakpoints on them. I'd really only force-inline them if there's a universal and substantial code size improvement.

We could introduce something like:
```rust
#[cfg_attr(feature = "force_inline", inline(always))]
```

**Comment by jonas-schievink** [comment]
Note that `#[inline]` does not affect the public API, and additional Cargo features can always be added after 1.0 too.

**Comment by adamgreig** [comment]
re: MSRV, I have checked and r0 builds on 1.31.0 but not 1.30.0 (since it specifies edition=2018), so our current minimum possible MSRV is 1.31.0.

**Comment by adamgreig** [comment]
@jamesmunns mentioned we might want to update the author field in Cargo.toml too.

**Comment by jonas-schievink** [comment]
This is done :tada:
